title: Isaac's
description: A personal blog.
baseurl: ""
url: ""
header_pages:
  - about.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
remote_theme: jekyll/minima
minima:
  social_links:
   - { platform: github,         user_url: "https://github.com/isjl" }
   - { platform: linkedin,       user_url: "https://linkedin.com/in/islong" }
   - { platform: rss,            user_url: "/feed.xml" }